import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from '@/components/nav-bar';

const spaceGroteskSans = Space_Grotesk({
  variable: '--font-space-grotesk-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${spaceGroteskSans.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className="max-w-3xl mx-auto py-3 md:py-10 h-[calc(100vh-3.6rem)] p-1">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
